name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build CI
        run: yarn run ci
